{
 "title": "HAproxy Servers | HAproxy",
 "description": "HAproxy backend servers",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(haproxy_up,instance)"
    }
   },
   { "name": "backend", "label": "Backend", "query": { "query": "label_values(backend)" } },
   { "name": "server", "label": "Server", "query": { "query": "label_values(server)" } },
   { "name": "code", "label": "HTTP Code", "query": { "query": "label_values(code)" } }
  ]
 },
 "panels": [
  { "title": "Backend Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_http_responses_total{backend=~\"$backend\", server=~\"$server\", code=~\"$code\", instance=~\"$instance\"}[180s])",
     "legendFormat": "{{ backend }}/{{ server }}/{{ code }}"
    }
   ]
  },
  {
   "title": "Check Duration (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(haproxy_server_check_duration_milliseconds{backend=~\"$backend\", server=~\"$server\", instance=~\"$instance\"}) without (alias)",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Check Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_check_failures_total{backend=~\"$backend\", server=~\"$server\", instance=~\"$instance\"}[180s])",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Downtime (s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_downtime_seconds_total{backend=~\"$backend\", server=~\"$server\", instance=~\"$instance\"}[180s])",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Redispatch Warnings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_redispatch_warnings_total{backend=~\"$backend\", server=~\"$server\", instance=~\"$instance\"}[180s])",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Response Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_response_errors_total{backend=~\"$backend\", server=~\"$server\", instance=~\"$instance\"}[180s])",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Retry Warnings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_retry_warnings_total{backend=~\"$backend\", server=~\"$server\", instance=~\"$instance\"}[180s])",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Bytes IN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_bytes_in_total{backend=~\"$backend\", server=~\"$server\", instance=~\"$instance\"}[180s])",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Bytes OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_bytes_out_total{backend=~\"$backend\", server=~\"$server\", instance=~\"$instance\"}[180s])",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "New Connections Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_connections_total{backend=~\"$backend\", server=~\"$server\", instance=~\"$instance\"}[180s])",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Connection Errors Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_connection_errors_total{backend=~\"$backend\", server=~\"$server\", instance=~\"$instance\"}[180s])",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Current Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_current_queue{backend=~\"$backend\", server=~\"$server\", instance=~\"$instance\"}",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Max Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_max_queue{backend=~\"$backend\", server=~\"$server\", instance=~\"$instance\"}",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Active Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_current_sessions{backend=~\"$backend\", server=~\"$server\", instance=~\"$instance\"}",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "New Session Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_current_session_rate{backend=~\"$backend\", server=~\"$server\", instance=~\"$instance\"}",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Max Active Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_max_sessions{backend=~\"$backend\", server=~\"$server\", instance=~\"$instance\"}",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Max Session Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_max_session_rate{backend=~\"$backend\", server=~\"$server\", instance=~\"$instance\"}",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Servers UP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_up{backend=~\"$backend\", server=~\"$server\", instance=~\"$instance\"}",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Servers Weights",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_weight{backend=~\"$backend\", server=~\"$server\", instance=~\"$instance\"}",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  }
 ]
}