- name: Jenkins
  hosts: localhost
  
  tasks:
    - name: Crear job
      jenkins_job:
        config: "{{ lookup('file', '../jenkins/jobs/prueba/config.xml') }}"
        name: funciona
        password: root
        state: present
        url: http://localhost:8082
        user: admin

